cache: []
.before_script_templeate: &install-dependencies
  before_script:
    - pip install -r requirements.txt


e2e:
  image: python
  <<: *install-dependencies
  services:
    - name: selenium/standalone-chrome
    - name: selenium/video
      variables:
        DISPLAY_CONTAINER_NAME: selenium__standalone-chrome
        FILE_NAME: chrome_video.mp4

  variables:
    FF_NETWORK_PER_BUILD: "true"

  script:
    - python teste.py
    - echo "Guardando evidencia em video"
    - cp -r -i /videos .
  artifacts:
    name: "$CI_JOB_NAME-evidence"
    when: always
    expire_in: "1 days"
    paths:
      - "./videos"  
  