image: python

variables:
  DISPLAY_CONTAINER_NAME: localhost
  FILE_NAME: chrome_video.mp4

.before_script_templeate: &install-dependencies
  before_script:
    - pip install -r requirements.txt

stages:
  - "e2e"


e2e:
  stage: e2e
  cache: []
  <<: *install-dependencies
  services:  
    - name: selenium/standalone-chrome
      alias: localhost
    - name: selenium/video
      alias: video
    


  script:
    - chmod 777 ./execute_front.sh
    - ./execute_front.sh
    - echo "Guardando evidencia em video"
    - cp -r -i /videos .
  artifacts:
    name: "$CI_JOB_NAME-evidence"
    when: always
    expire_in: "1 days"
    paths:
      - "./videos"
